name: Build_App_Final
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          echo "THEOS=~/theos" >> $GITHUB_ENV
      - name: Build
        run: |
          unzip -o *.zip
          echo '{"Filter":{"Bundles":["com.dts.freefireth","com.dts.freefiremax"]}}' > H5GG_FF_Menu.plist
          sed -i '' 's/TWEAK_NAME/ADDITIONAL_CFLAGS = -Wno-deprecated-declarations\\\nLDID = $(THEOS)\/bin\/ldid\\\nTWEAK_NAME/g' Makefile
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          
          # LỆNH THAY ĐỔI CUỘC CHƠI: Quét toàn bộ để tìm dylib
          mkdir -p Final_Pack
          find . -name "*.dylib" -not -path "*/theos/*" -exec cp {} Final_Pack/ \;
          cp H5GG_FF_Menu.plist Final_Pack/
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Mod_Result_Dứt_Điểm
          path: Final_Pack/*
