name: Build_App_Final
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          echo "THEOS=~/theos" >> $GITHUB_ENV
      - name: Build
        run: |
          unzip -o *.zip
          echo '{"Filter":{"Bundles":["com.dts.freefireth","com.dts.freefiremax"]}}' > H5GG_FF_Menu.plist
          # Sửa lỗi Makefile và ép build ra file dylib
          sed -i '' 's/TWEAK_NAME/ADDITIONAL_CFLAGS = -Wno-deprecated-declarations\\\nLDID = $(THEOS)\/bin\/ldid\\\nTWEAK_NAME/g' Makefile
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          
          # Gom tất cả file quan trọng vào một thư mục (SỬA LỖI HOÀN TOÀN)
          mkdir -p TrollFools_Files
          find . -name "*.dylib" -not -path "./theos/*" -exec cp {} TrollFools_Files/ \;
          cp H5GG_FF_Menu.plist TrollFools_Files/
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Mod_Full_Pack
          path: TrollFools_Files/*
