name: Build_App_Final
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          echo "THEOS=~/theos" >> $GITHUB_ENV
      - name: Build
        run: |
          unzip -o *.zip
          echo '{"Filter":{"Bundles":["com.dts.freefireth","com.dts.freefiremax"]}}' > H5GG_FF_Menu.plist
          # Sửa lỗi ldid và ép cấu trúc build chuẩn
          sed -i '' 's/TWEAK_NAME/ADDITIONAL_CFLAGS = -Wno-deprecated-declarations\\\nLDID = $(THEOS)\/bin\/ldid\\\nTWEAK_NAME/g' Makefile
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          
          # Lệnh trích xuất file dylib thông minh (Sửa lỗi hoàn toàn)
          mkdir -p Result_For_TrollFools
          find . -name "*.dylib" -not -path "./theos/*" -exec cp {} Result_For_TrollFools/ \;
          cp H5GG_FF_Menu.plist Result_For_TrollFools/ 2>/dev/null || true
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Mod_Files_For_TrollFools
          path: Result_For_TrollFools/*
