name: Build_App_Final
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          echo "THEOS=~/theos" >> $GITHUB_ENV
      - name: Build
        run: |
          unzip -o *.zip
          echo '{"Filter":{"Bundles":["com.dts.freefireth","com.dts.freefiremax"]}}' > H5GG_FF_Menu.plist
          sed -i '' 's/TWEAK_NAME/ADDITIONAL_CFLAGS = -Wno-deprecated-declarations\\\nLDID = $(THEOS)\/bin\/ldid\\\nTWEAK_NAME/g' Makefile
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          
          # Gom file dylib và plist vào một chỗ
          mkdir -p Plugins_For_TrollFools
          find .theos/obj -name "*.dylib" -exec cp {} Plugins_For_TrollFools/ \;
          cp H5GG_FF_Menu.plist Plugins_For_TrollFools/
          
          # Nén lại thành zip để GitHub không làm hỏng định dạng
          zip -r Mod_Fix_All.zip Plugins_For_TrollFools
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Mod_Result
          path: Mod_Fix_All.zip
