name: Build_App_Final
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          echo "THEOS=~/theos" >> $GITHUB_ENV
          echo "~/theos/bin" >> $GITHUB_PATH
      - name: Build
        run: |
          unzip -o *.zip
          # Tạo file cấu hình hỗ trợ cả 2 bản Free Fire
          echo '{"Filter":{"Bundles":["com.dts.freefireth","com.dts.freefiremax"]}}' > H5GG_FF_Menu.plist
          # Sửa lỗi keyWindow và ép dùng ldid của Theos
          sed -i '' 's/TWEAK_NAME/ADDITIONAL_CFLAGS = -Wno-deprecated-declarations\nLDID = $(THEOS)\/bin\/ldid\nTWEAK_NAME/g' Makefile
          make package FINALPACKAGE=1
      - uses: actions/upload-artifact@v4
        with:
          name: Mod_Result
          path: "packages/*.tipa"
