name: Build_App_Final
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: its-asv/setup-theos@v1.1
      - name: Build
        run: |
          unzip -o *.zip
          make package FINALPACKAGE=1
      - uses: actions/upload-artifact@v4
        with:
          name: Mod_Result
          path: "packages/*.tipa"
