name: Build_App_Final
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          echo "THEOS=~/theos" >> $GITHUB_ENV
      - name: Build
        run: |
          unzip -o *.zip
          echo '{"Filter":{"Bundles":["com.dts.freefireth","com.dts.freefiremax"]}}' > H5GG_FF_Menu.plist
          sed -i '' 's/TWEAK_NAME/ADDITIONAL_CFLAGS = -Wno-deprecated-declarations\\\nLDID = $(THEOS)\/bin\/ldid\\\nTWEAK_NAME/g' Makefile
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          
          # QUY TRÌNH QUÉT TOÀN DIỆN: Lấy file dylib bất kể nó nằm ở đâu
          mkdir -p Plugins_Export
          find . -name "*.dylib" -not -path "*/theos/*" -exec cp {} Plugins_Export/ \;
          cp H5GG_FF_Menu.plist Plugins_Export/
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Mod_Result_Full
          path: Plugins_Export/*
