name: Build_App_Final
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: theos/setup-theos@master
      - name: Build Package
        run: |
          unzip -o *.zip
          make package FINALPACKAGE=1
      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: Mod_Result
          path: "packages/*.tipa"
