name: Build_App_Final
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          echo "THEOS=~/theos" >> $GITHUB_ENV
      - name: Build
        run: |
          unzip -o *.zip
          echo '{"Filter":{"Bundles":["com.dts.freefireth","com.dts.freefiremax"]}}' > H5GG_FF_Menu.plist
          sed -i '' 's/TWEAK_NAME/ADDITIONAL_CFLAGS = -Wno-deprecated-declarations\\\nLDID = $(THEOS)\/bin\/ldid\\\nTWEAK_NAME/g' Makefile
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          
          # PHẪU THUẬT LẤY FILE DYLIB TRỰC TIẾP
          mkdir -p Final_Result
          DEB_FILE=$(find packages -name "*.deb" | head -n 1)
          if [ -f "$DEB_FILE" ]; then
            ar x "$DEB_FILE"
            tar -xf data.tar.*
            # Quét toàn bộ để lấy dylib và đổi tên đơn giản
            find . -name "*.dylib" -not -path "./theos/*" -exec cp {} Final_Result/Plugin.dylib \;
          fi
          cp H5GG_FF_Menu.plist Final_Result/
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Mod_Fix_Final
          path: Final_Result/*
