name: Build_App_Fix_All
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: theos/setup-theos
      - name: Build Package
        run: |
          unzip -o *.zip
          FOLDER=$(find . -maxdepth 1 -type d ! -name ".*" ! -name "github" | head -n 1)
          cd "$FOLDER"
          make package FINALPACKAGE=1
      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: Mod_Result
          path: "**/*.tipa"
